### PR TITLE
Added extensions to the docs

### PR DESCRIPTION
**Pull request by jkarsrud**

### CODE REVIEW

**Comment by jodal** [comment]
I added these as part of the architecture overview page last night.

I had trouble combining the content from the architecture overview and the "docs pages", since the architecture overview page is intended for Buster.JS contributors, while the other pages are more oriented towards end user or module re-user. I think that if we are to keep the individual pages under `extensions/` and `modules/`, they should be reserved for usage docs.

**Comment by jkarsrud** [comment]
In that case, I suppose we should author up some new docs for the pages in this pull request, explaining how to use them (buster-amd for instance).

**Comment by jodal** [comment]
There's a good start at http://busterjs.org/docs/extensions/. I found that page by grepping for buster-lint in the docs source. Don't know how to navigate to that page on the old site.

**Comment by jkarsrud** [comment]
That sure looks like a good starting point indeed, plus making it a page you can actually navigate to. I can get started on that today, if you'd like?

**Comment by jodal** [comment]
Sounds like a plan!

I'll look at the core modules, and how to do API docs until we get that extracted from source code comments.

**Pull request closed without merging**
