### PR TITLE
Adding extra installation step in case of failed require of when.js

### PR DESCRIPTION
**Pull request by andybeeching**
Encountered this issue when installing the latest buster-dev tools

### CODE REVIEW

**Comment by cjohansen** [comment]
Interesting. What kind of error did you experience?

**Comment by andybeeching** [comment]
Failed when.js require (which is spec'd as a dependency in package.json)

**Comment by cjohansen** [comment]
But which module failed the install? The dev-tools package itself?

**Comment by cjohansen** [comment]
thanks!

**Pull request merged**
