### PR TITLE
use pwd + make sure that you install the npm modules

### PR DESCRIPTION
**Pull request by sdepold**

### CODE REVIEW

**Comment by sdepold** [comment]
dunno why @cjohansen 's commit is in that patch

**Comment by meisl** [comment]
The `pwd` is already covered in [pr8](https://github.com/busterjs/buster-docs/pull/8), fixing it for Win as well + more. This should have been merged into master (or both, master & develop; went into develop only). 

Re the `npm install`: that's being mentioned already on develop but not on master ([pr6](https://github.com/busterjs/buster-docs/pull/6)). I'll update buster-dev-tools soon to make that unnecessary anyways.

There really is some confusion coming from those two branches...

Re the other commit: dunno either.

@sdepold: thanks nevertheless :)

**Comment by cjohansen** [comment]
@meisl are you saying that everything in @sdepold's commits are already covered? If so, feel free to close this issue.

**Comment by meisl** [comment]
buster-dev-tools updated, no need to `npm install` by hand anymore. [pr10](https://github.com/busterjs/buster-docs/pull/10) updates the docs accodingly.

@cjohansen: yes, I am. But you have to decide on the commit that's marked as yours. Btw: I can't close prs here.

**Comment by cjohansen** [comment]
Oh, right :) Yeah, my commit is already in the repo. I have no idea why it ends up here. Maybe @sdepold pulled it in before making his own commit?

**Pull request closed without merging**
