### PR TITLE
Add some documentation for browser testing and AMD

### PR DESCRIPTION
**Pull request by trodrigues**
Improved docs on browser testing section a bit.
Added some information on how to run with PhantomJS.
Improved docs on the buster-amd section and made references to buster-amd more visible.

### CODE REVIEW

**Comment by cjohansen** [comment]
Looks great Tiago, thanks! I'm not sure we need the buster-demos.sublime-workspace though? :)

**Comment by trodrigues** [comment]
Oh crap. Did that actually get committed? I noticed it was accidentally created there and then removed it. Maybe sublime saved it back to the same place. It tends to do that.

git commit -am is such a bad habit...

**Comment by cjohansen** [comment]
Thanks, should be live in a matter of minutes.

**Comment by trodrigues** [comment]
yay!

**Pull request merged**
